model:
    ssm_io_dim: 256
    ssm_dim: 64
    ssm_init_diag_blocks: 4
    ssm_num_layers: 2
    output_dim: 2
    rng_seed: 42
    dt_min: 0.001
    dt_max: 0.01
    dropout_p: 0.03

optimizer:
  lr: 0.002
  weight_decay: 0.01
  mode: all