- selection:
  - brainset: perich_miller_population_2018

- selection:
  - brainset: pei_pandarinath_nlb_2021

- selection:
  - brainset: odoherty_sabes_nonhuman_2017

- selection:
  - brainset: churchland_shenoy_neural_2012

- selection:
  - brainset: flint_slutzky_accurate_2012

