- selection:
  - brainset: perich_miller_population_2018
    subjects:
      - m
    exclude_sessions:
      - m_20140114_random_target_reaching
      - m_20140115_random_target_reaching
      - m_20140116_random_target_reaching
      - m_20140214_random_target_reaching
      - m_20140221_random_target_reaching
      - m_20140224_random_target_reaching
      - m_20150512_center_out_reaching
