# multi_dataset_config.yaml
- selection:
  - brainset: perich_miller_population_2018
    sessions:
      - perich_miller_population_2018/c_20161013_center_out_reaching
      - perich_miller_population_2018/c_20161021_center_out_reaching
      - perich_miller_population_2018/t_20130819_center_out_reaching
      - perich_miller_population_2018/t_20130820_random_target_reaching
      - perich_miller_population_2018/t_20130821_center_out_reaching
      - perich_miller_population_2018/t_20130822_random_target_reaching
      - perich_miller_population_2018/t_20130823_center_out_reaching
      - perich_miller_population_2018/t_20130830_random_target_reaching
      - perich_miller_population_2018/t_20130903_center_out_reaching
      - perich_miller_population_2018/t_20130904_random_target_reaching
  config:
    readout:
      readout_id: cursor_velocity_2d

- selection:
  - brainset: churchland_shenoy_neural_2012
  config:
    readout:
      readout_id: cursor_velocity_2d