# multi_dataset_config.yaml
- selection:
  - brainset: perich_miller_population_2018
    sessions:
    - c_20131003_center_out_reaching
    - c_20150309_center_out_reaching
    - c_20161011_center_out_reaching
    - c_20131009_random_target_reaching
    - c_20131209_random_target_reaching
    - c_20150320_random_target_reaching
    - m_20140203_center_out_reaching
    - m_20140303_center_out_reaching
    - m_20150626_center_out_reaching
    - m_20140114_random_target_reaching
    - m_20140221_random_target_reaching
    - m_20140224_random_target_reaching

- selection:
  - brainset: odoherty_sabes_nonhuman_2017
    sessions:
    - indy_20160407_02
    - indy_20170123_02
    - indy_20170131_02
    - loco_20170210_03
    - loco_20170302_02
    - loco_20170228_02

    
- selection:
  - brainset: churchland_shenoy_neural_2012
    sessions:
    - jenkins_20090912_center_out_reaching
    - jenkins_20090916_center_out_reaching
    - jenkins_20090923_center_out_reaching
    - nitschke_20090812_center_out_reaching
    - nitschke_20090819_center_out_reaching
    - nitschke_20090922_center_out_reaching

- selection:
  - brainset: pei_pandarinath_nlb_2021
