- selection:
  - brainset: perich_miller_population_2018
    sessions:
      - c_20131009_random_target_reaching
      - c_20131010_random_target_reaching
      - c_20131011_random_target_reaching
      - c_20131028_random_target_reaching
      - c_20131029_random_target_reaching
      - c_20131209_random_target_reaching
      - c_20131210_random_target_reaching
      - c_20131212_random_target_reaching
      - c_20131213_random_target_reaching
      - c_20131217_random_target_reaching
      - c_20131218_random_target_reaching
      - c_20150316_random_target_reaching
      - c_20150317_random_target_reaching
      - c_20150318_random_target_reaching
      - c_20150320_random_target_reaching
      - m_20140114_random_target_reaching
      - m_20140115_random_target_reaching
      - m_20140116_random_target_reaching
      - m_20140214_random_target_reaching
      - m_20140221_random_target_reaching
      - m_20140224_random_target_reaching

- selection:
  - brainset: odoherty_sabes_nonhuman_2017
    exclude_sessions:
      - loco_20170214_02
      - loco_20170216_02
      - loco_20170217_02
