# multi_dataset_config.yaml
- selection:
  - brainset: perich_miller_population_2018
    sessions:
      - t_20130819_center_out_reaching
      - t_20130821_center_out_reaching
      - t_20130823_center_out_reaching
      - t_20130903_center_out_reaching
  config:
    readout:
      readout_id: cursor_velocity_2d
