wandb:
  project: foundational_ssm_finetune_mc_maze
  tags: [neural, behavior, mc_maze]

train_dataset:
  name: mc_maze
  task: center_out_reaching
  holdout_angles: true
  batch_size: 256

model:
  ssm_io_dim: 128
  ssm_dim: 128
  ssm_init_diag_blocks: 4
  ssm_num_layers: 3
  output_dim: 2
  rng_seed: 42

optimizer:
  lr: 0.001
  weight_decay: 0.001
  use_cosine_scheduler: false
  min_lr: 0.00001  # Minimum learning rate for cosine annealing
  warmup_steps: 100  # Number of warmup steps (0 for no warmup)

training:
  epochs: 1000
  log_every: 50
  freeze_ssm: false
  freeze_mlp: false

wandb_pretrained_model_id: melinajingting-ucl/foundational_ssm_pretrain_decoding/sub-cmtj_l3_d128_best_model:v15


rng_seed: 42

device: cuda

