wandb:
  project: foundational_ssm_pretrain_decoding
  run_prefix:  
  tags: [neural, behavior, masking]
  log_freq: 1
  entity: melinajingting-ucl
  resume_run_id: null #cr6zuzfw (l1-d128)

train_dataset:
  brainset: perich_miller_population_2018
  subjects: [c,m,t]
  # Example: exclude specific sessions from training
  # exclude_sessions: [session1, session2]

val_dataset:
  brainset: perich_miller_population_2018
  subjects: [c,m,t]
  # Example: exclude specific sessions from validation
  # exclude_sessions: [session3, session4]

dataloader:
  batch_size: 1024
  lazy: true
  num_workers: 0
  keep_files_open: true

model:
  ssm_io_dim: 64
  ssm_dim: 64
  ssm_init_diag_blocks: 4
  ssm_num_layers: 4
  output_dim: 2
  rng_seed: 42

optimizer:
  lr: 0.001
  weight_decay: 0.001
  use_cosine_scheduler: false
  min_lr: 0.00001  # Minimum learning rate for cosine annealing
  warmup_steps: 100  # Number of warmup steps (0 for no warmup)

training:
  epochs: 1000
  checkpoint_every: 2

filter_spec:
  freeze_ssm: false
  freeze_mlp: false

rng_seed: 42

device: cuda

