# PERICH MILLER
# Center-out reaching 
- selection:
  - dandiset: perich_miller_population_2018
    sortsets:
      - c_20131003
      - c_20131022
      - c_20131023
      - c_20131031
      - c_20131101
      - c_20131203
      - c_20131204
      - c_20131219
      - c_20131220
      - c_20150309
      - c_20150311
      - c_20150312
      - c_20150313
      - c_20150319
      - c_20150629
      - c_20150630
      - c_20150701
      - c_20150703
      - c_20150706
      - c_20150707
      - c_20150708
      - c_20150709
      - c_20150710
      - c_20150713
      - c_20150714
      - c_20150715
      - c_20150716
      - c_20151103
      - c_20151104
      - c_20151106
      - c_20151109
      - c_20151110
      - c_20151112
      - c_20151113
      - c_20151116
      - c_20151117
      - c_20151119
      - c_20151120
      - c_20151201
      - c_20160909
      - c_20160912
      - c_20160914
      - c_20160915
      - c_20160919
      - c_20160921
      - c_20160923
      - c_20160929
      - c_20161005
      - c_20161006
      - c_20161007
      - c_20161011
      - m_20140203
      - m_20140217
      - m_20140218
      - m_20140303
      - m_20140304
      - m_20140306
      - m_20140307
      - m_20140626
      - m_20140627
      - m_20140929
      - m_20141203
      - m_20150511
      - m_20150610
      - m_20150611
      - m_20150612
      - m_20150615
      - m_20150616
      - m_20150617
      - m_20150623
      - m_20150625
      - m_20150626
  config:
    multitask_readout:
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.REACH

# Random target reaching
- selection:
  - dandiset: "perich_miller_population_2018"
    sortsets:
    - c_20131009
    - c_20131010
    - c_20131011
    - c_20131028
    - c_20131029
    - c_20131209
    - c_20131210
    - c_20131212
    - c_20131213
    - c_20131217
    - c_20131218
    - c_20150316
    - c_20150317
    - c_20150318
    - c_20150320
    - m_20140114
    - m_20140115
    - m_20140116
    - m_20140214
    - m_20140221
    - m_20140224
  config:
    multitask_readout:
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.RANDOM

# CHURCHLAND SHENOY CENTER OUT
- selection:
  - dandiset: churchland_shenoy_neural_2012
    sortsets:
    # - jenkins_20090918
    # - nitschke_20090922
    - jenkins_20090923
    - nitschke_20100923
  config:
    multitask_readout:
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.REACH

# Odoherty Sabes
- selection:
  - dandiset: odoherty_sabes_nonhuman_2017
    sortsets:
      - indy_20160624_03
      - indy_20160630_01
      - indy_20160407_02
      - loco_20170302_02
      - indy_20161027_03
      - indy_20160927_04
      - loco_20170227_04
      - indy_20161212_02
      - indy_20170124_01
      - loco_20170228_02
      - indy_20161206_02
      - indy_20170127_03
      - indy_20160916_01
      - indy_20160927_06
      - loco_20170215_02
      - indy_20160418_01
      - indy_20160420_01
      - indy_20161207_02
      - indy_20161011_03
      - indy_20160419_01
      - indy_20160930_05
      - indy_20160411_01
      - indy_20161006_02
      - indy_20160930_02
      - indy_20161024_03
      - indy_20161005_06
      - indy_20170131_02
      - indy_20160627_01
      - indy_20160921_01
      - indy_20160411_02
      - indy_20161220_02
      - loco_20170301_05
      - indy_20160622_01
      - indy_20160915_01
      - indy_20161026_03
      - indy_20161025_04
      - loco_20170213_02
      - indy_20170123_02
      - loco_20170210_03
      - indy_20161017_02
      - indy_20160426_01
      - indy_20161013_03
      - indy_20161014_04
      - indy_20161007_02
  config:
    multitask_readout:
      # - decoder_id: ARMVELOCITY2D
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.RANDOM
    sampling_intervals_modifier: |
      import numpy as np
      from kirby.data import Interval
      if split == "valid" or split == "test":
        intervals = []
        for i in range(len(sampling_intervals)):
          start, end = sampling_intervals.start[i], sampling_intervals.end[i]
          max_len = 5.
          if end - start < max_len:
            intervals.append((start, end))
          else:
            for s in np.arange(start, end, max_len):
              if s + max_len < end:
                intervals.append((s, s + max_len))
            if end - intervals[-1][1] > 0:
              intervals.append((end - max_len, end))
        sampling_intervals = Interval.from_list(intervals)

- selection:
    - dandiset: pei_churchland_nlbmaze_2021
  config:
    multitask_readout:
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.EVAL: 1.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.EVAL