wandb:
  project: foundational_ssm_downstream_decoding
  tags: [neural, behavior, downstream, decoding]
  entity: melinajingting-ucl

downstream_datasets:
  t_rt: /cs/student/projects1/ml/2024/mlaimon/foundational_ssm/configs/dataset/t_rt.yaml
  t_co: /cs/student/projects1/ml/2024/mlaimon/foundational_ssm/configs/dataset/t_co.yaml

train_loader:
  dataset_args:
    keep_files_open: false
    lazy: true
    split: train
  sampler: RandomFixedWindowSampler
  sampler_args:
    drop_short: true
    window_length: 1
  dataloader_args:
    batch_size: 512
    num_workers: 12
    persistent_workers: true
  window_length: 1
  sampling_rate: 200

val_loader:
  dataset_args:
    keep_files_open: false
    lazy: true
    split: val
  sampler: TrialSampler
  sampler_args: null
  dataloader_args:
    batch_size: 512
    num_workers: 4
    persistent_workers: true
  window_length: 6
  sampling_rate: 200

models:
  l1_d128: melinajingting-ucl/foundational_ssm_pretrain_decoding/inverse_variance_l1_d128_checkpoint:best

optimizer:
  lr: 0.001
  weight_decay: 0.001
  use_cosine_scheduler: false
  min_lr: 0.00001  # Minimum learning rate for cosine annealing
  warmup_steps: 100  # Number of warmup steps (0 for no warmup)

filter_spec:
  freeze_ssm: false
  freeze_mlp: false
  
training:
  epochs: 500
  checkpoint_every: 50
  log_val_every: 100
  log_pred_and_activations_every: 100


downstream_modes:
  scratch:
    from_scratch: true 
    filter_spec:
      freeze_ssm: false
      freeze_mlp: false
  # scratch_frozen_ssm:
  #   from_scratch: true 
  #   filter_spec:
  #     freeze_ssm: true
  #     freeze_mlp: false
  # ft_mlp:
  #   from_scratch: false 
  #   filter_spec:
  #     freeze_ssm: true
  #     freeze_mlp: false
  # full:
  #   from_scratch: false 
  #   filter_spec:
  #     freeze_ssm: false
  #     freeze_mlp: false

rng_seed: 42

device: cuda