wandb:
  project: foundational_ssm_finetune_rtt
  tags: [neural, behavior, masking]
  log_freq: 1
  entity: melinajingting-ucl
  resume_run_id: null

dataset:
  dataset: mc_rtt
  task: null
  holdout_angles: false
  batch_size: 256
  num_workers: 4

model:
  input_dim: 130
  ssm_io_dim: 128
  ssm_dim: 128
  ssm_init_diag_blocks: 4
  ssm_num_layers: 4
  output_dim: 2
  rng_seed: 42

finetune:
  enabled: true
  project: foundational_ssm_pretrain_decoding
  run_name: sub-cmtj_l3_d128

optimizer:
  lr: 0.001
  weight_decay: 0.001
  use_cosine_scheduler: false
  min_lr: 0.00001  # Minimum learning rate for cosine annealing
  warmup_steps: 100  # Number of warmup steps (0 for no warmup)

training:
  epochs: 1000
  checkpoint_every: 20

filter_spec:
  freeze_ssm: false
  freeze_mlp: false

rng_seed: 42

device: cuda