wandb:
  project: foundational_ssm
  run_name: ssm_neural_behavior
  tags: [neural, behavior, masking]
  log_freq: 1

dataset:
  name: perich_miller_population_2018
  subjects: [j]
  batch_size: 128
  root: /cs/student/projects1/ml/2024/mlaimon/data/foundational_ssm/processed/

model:
  num_neural_features: 192
  num_behavior_features: 2
  num_context_features: 32
  embedding_dim: 64
  ssm_projection_dim: 64
  ssm_hidden_dim: 64
  ssm_num_layers: 2
  ssm_dropout: 0.1
  pred_neural_dim: 192
  pred_behavior_dim: 2
  sequence_length: 1.0
  sampling_rate: 100
  lin_dropout: 0.1
  activation_fn: relu

training:
  learning_rate: 4e-3
  mask_prob: 0.5
  num_epochs: 100
  neural_weight: 10.0
  behavior_weight: 1.0

device: cuda