wandb:
  project: foundational_ssm_downstream_pm
  tags: [neural, behavior, masking]
  entity: melinajingting-ucl
  resume_run_id: null 

dataset_args:
  recording_id: perich_miller_population_2018/t_20130909_center_out_reaching

train_loader:
  dataloader_args:
    batch_size: 64
    num_workers: 12
    persistent_workers: true
  sampler: RandomVariableWindowSampler
  sampler_args:
    drop_short: true
    min_window_length: 1
    max_window_length: 5

val_loader:
  dataloader_args:
    batch_size: 64
    num_workers: 0
    persistent_workers: false
  sampler: TrialSampler

model:
  checkpoint: melinajingting-ucl/foundational_ssm_pretrain/l2_reaching_normalized_checkpoint:best

optimizer:
  lr: 0.002
  weight_decay: 0.03
  mode: all

training:
  epochs: 701
  log_val_every: 100
  save_checkpoints: false
  checkpoint_every: 100
  from_scratch: false

prepend_history: 0.3
sampling_rate: 200
rng_seed: 42
