wandb:
  project: foundational_ssm_pretrain
  tags: [neural, behavior, masking]
  entity: melinajingting-ucl
  resume_run_id: null 

model_cfg: ../configs/model/l2.yaml
dataset_cfg: ../configs/dataset/reaching.yaml

train_loader:
  dataset_args:
    keep_files_open: false
    lazy: true
    split: train
  sampler: RandomFixedWindowSampler
  sampler_args:
    drop_short: true
    window_length: 1.279
  dataloader_args:
    batch_size: 64
    num_workers: 0
    persistent_workers: false
  sampling_rate: 200

val_loader:
  dataset_args:
    keep_files_open: false
    lazy: true
    split: val
  sampler: SequentialFixedWindowSampler
  sampler_args: 
    drop_short: true
    window_length: 1.279
  dataloader_args:
    batch_size: 128
    num_workers: 0
    persistent_workers: false
  sampling_rate: 200

training:
  epochs: 1001
  checkpoint_every: 1
  log_val_every: 50

skip_timesteps: 56  # Number of samples to skip in each batch (0 means no skipping)
rng_seed: 42

