# Wandb sweep configuration
program: scripts/pretrain_decoding.py
method: grid
metric:
  name: final/best_r2
  goal: maximize
run_cap: 30  # Limit total number of runs
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  train_loader.sampler_args.window_length:
        values: [0.879, 1.279, 3.279, 5.279, 7.279]

wandb:
  project: foundational_ssm_pretrain_sweep_duration
  tags: [neural, behavior, downstream, decoding, sweep]
  entity: melinajingting-ucl