# Wandb sweep configuration
program: scripts/training/downstream_mc_rtt.py
method: grid
metric:
  name: final/best_r2
  goal: maximize
run_cap: 2000  # Limit total number of runs
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  optimizer.mode:
    values: [all, freeze_a]
  model.ssm_dim:
    values: [32, 64, 128]
  model.ssm_io_dim:
    values: [256, 512]
  model.ssm_num_layers:
    values: [1, 2, 4]
  optimizer.lr:
    values: [0.0005, 0.001, 0.002, 0.003, 0.004, 0.005]
  optimizer.weight_decay:
    values: [0.01, 0.03, 0.05]
  model.dropout_p:
    values: [0.01, 0.03, 0.05]

# Fixed parameters (not swept)
wandb:
  project: foundational_ssm_rtt_sweep
  tags: [neural, behavior, downstream, decoding, sweep]
  entity: melinajingting-ucl
  run_prefix: sweep_rtt
