# Wandb sweep configuration
program: scripts/training/downstream_mc_rtt.py
method: grid
metric:
  name: final/best_r2
  goal: maximize
run_cap: 2000  # Limit total number of runs
early_terminate:
  type: hyperband
  min_iter: 10
parameters:
  optimizer.mode:
    values: [all, freeze_a, encoder_only]
  training.from_scratch:
    values: [true, false]
  model.checkpoint:
    values: [melinajingting-ucl/foundational_ssm_pretrain/l2_reaching_normalized_checkpoint:best, 
             melinajingting-ucl/foundational_ssm_pretrain/l4_reaching_normalized_checkpoint:best]

# Fixed parameters (not swept)
wandb:
  project: foundational_ssm_rtt
  tags: [neural, behavior, downstream, decoding, sweep]
  entity: melinajingting-ucl
  run_prefix: sweep_rtt