program: scripts/pre_train.py
method: bayes
metric:
  name: val/combined_loss  # Or val/behavior_r2 if that's your primary metric
  goal: minimize  # Use 'maximize' for R² metrics
parameters:
  config:
    value: cmt
  # Model architecture parameters
  model.ssm_hidden_dim:
    values: [32, 64, 128, 256]
  model.ssm_num_layers:
    values: [1, 2, 3]
  model.embedding_dim:
    values: [32, 64, 128]
  # Regularization parameters
  model.ssm_dropout:
    distribution: uniform
    min: 0.0
    max: 0.3
  model.lin_dropout:
    distribution: uniform
    min: 0.0
    max: 0.3
  # Training parameters
  training.learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-2
  training.neural_weight:
    values: [1.0, 10.0, 100.0]